L2T18/mySite/mySite/blog/urls.py
from django.views.generic import ListView, DetailView
from django.urls import path
from .models import Post

urlpatterns = [

    path('',
    ListView.as_view(
    queryset=

     Post.objects.all().order_by("-date")[:25],
     template_name="blog.html")

    ),

     path('<int:pk>/',
     DetailView.as_view(
        model = Post,
        template_name="post.html"
        )
     ),
]

L2T18/mySite/mySite/mySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('personal/', include('personal.urls')),
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('user_auth/', include('django.contrib.auth.urls')),
    path('user_auth/', include('user_auth.urls')),
]

L2T18/mySite/mySite/personal/urls.py
from django.urls import path, include
from . import views

urlpatterns = [

    path('', views.index, name='index'),
    path('welcome/', views.previously_created_1, name='welcome'),
]

L2T18/mySite/mySite/polls/urls.py
from django.urls import path, include
from . import views

app_name = 'polls'
urlpatterns = [

    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/result/', views.results, name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

L2T18/mySite/mySite/user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'

urlpatterns = [

    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user,
         name='authenticate_user'),
]

L2T18/mySite/mySite/blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):

# Default behaviour - Django creates primary keys for you
    title = models.CharField(max_length=140)
    body = models.TextField()
    signature = models.CharField(max_length=140, default='joshua')

    date = models.DateTimeField()

def __str__(self):

   return self.title

L2T18/mySite/mySite/personal/models.py
from django.db import models

# Create your models here.

L2T18/mySite/mySite/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

def ___str___(self):

    return f"{Question.question_text}, {Choice.choice_text}"

L2T18/mySite/mySite/user_auth/models.py
from django.db import models

# Create your models here.

L2T18/mySite/mySite/blog/views.py
from django.shortcuts import render

# Create your views here.

L2T18/mySite/mySite/personal/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):

    return render(request, "index.html", {'name': 'Joshua'})

def previously_created_1(request):

    return render(request, "previously created 1.html")

L2T18/mySite/mySite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice


# Create your views here
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}

    return render(request, 'polls.html', context)


def poll(request):
    return HttpResponse("Welcome to the polls index!")


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
            pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully
        # dealing with POST data. This prevents data from being
        # posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:result', args=(question_id,)))

L2T18/mySite/mySite/user_auth/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth import authenticate, login


# Create your views here.
def user_login(request):
    return render(request, 'authentication/login.html')


def authenticate_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)

    if user is None:
        return HttpResponseRedirect(reverse('user_auth:login'))

    else:
        login(request, user)
        return HttpResponseRedirect(reverse('user_auth:show_user'))

L2T18/mySite/mySite/personal/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Information</title>
</head>
<body>
<h1> About {{name}}: </h1>

    <br>
    <p> My name is Joshua and I am a child of god. I am passionate about coding
        and I enjoy solving problems.             </p>

    <p> What mostly motivates me is the feeling of winning , It keeps me alive
        and is the fuel that keeps me going. </p>

    <p> I have completed a Software Engineering bootcamp and have equiped myself
        with the necessary skills to bring and add value to your business as
        this is the line of work I want to pursue in.
       </p>


</body>
</html>

L2T18/mySite/mySite/personal/templates/previously created 1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>first app </title>
</head>
<body>
<h1>Hello Word </h1>
</body>
</html>

L2T18/mySite/mySite/polls/templates/detail.html
<h1> {{question.question_text}}</h1>

    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice {{
                forloop.counter}}" value="{{ choice.id }}" />
            <!--suppress XmlInvalidId -->
        <label for="choice {{ forloop.counter }}">
            {{ choice.choice_text }}
            </label>
            <br />
        {% endfor %}

        <input type="submit" value="Vote" />

    </form>

L2T18/mySite/mySite/polls/templates/polls.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href = "{% url 'polls:detail' question.id %}">
            {{ question.question_text }}
            </a>
        </li>
        {% endfor %}
    </ul>

{% else %}

    <p>No polls are available.</p>

{% endif %}

L2T18/mySite/mySite/polls/templates/results.html
<h1> {{ question.question_text }} </h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes}}
            vote{{choice.votes|pluralize}}
        </li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">
        Vote again?
    </a>

L2T18/mySite/mySite/user_auth/templates/authentication/login.html
<h1> Login as User </h1>
    <form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %}
        <label>Username</label>
        <input type="text" name="username" placeholder="User" required>
    <br/><br/>
    <label>Password</label>
        <input type="password" name="password" required>
    <br/><br/>
    <input type="submit" value="Login" />
</form>

L2T18/mySite/mySite/user_auth/templates/authentication/user.html
<<h1> Welcome, {{username}} </h1>

<p> Your password is {{password}}</p>